apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "casepro.fullname" . }}-nginx-web
  labels:
    {{- include "casepro.labels" . | nindent 4 }}
data:
  casepro.conf: |
    server {
      listen 8000;
      client_max_body_size 100m;
      access_log stdout;
      error_log stderr;
      location / {
        proxy_pass http://localhost:{{ .Values.web.containerPort }};
        proxy_read_timeout 300s;
        proxy_redirect off;
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_next_upstream error timeout invalid_header http_500 http_502 http_503 http_504;
      }
      location /sitestatic {
        alias /www/sitestatic;
      }
      location /media {
        alias /www/media;
      }
      location /nghealth {
        return 200;
      }
    }
