apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "casepro.fullname" . }}-nginx-web
  labels:
    {{- include "casepro.labels" . | nindent 4 }}
data:
  nginx_web_conf: |
    upstream web_server {
      server 127.0.0.1:{{ .Values.web.containerPort }} fail_timeout=0;
    }

    server {
      listen 8010;
      client_max_body_size 100m;

      access_log stdout;
      error_log stderr;

      location / {
        proxy_pass http://web_server;
        proxy_read_timeout 300s;
        proxy_redirect off;
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_next_upstream error timeout invalid_header http_500 http_502 http_503 http_504;
      }

      location /sitestatic {
        alias /www/sitestatic;
      }
    }
