apiVersion: v1
kind: Service
metadata:
  name: {{ include "casepro.fullname" . }}
  labels:
    {{- include "casepro.labels" . | nindent 4 }}
spec:
  type: {{ .Values.web.service.type }}
  ports:
    - port: {{ .Values.web.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "casepro.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: web
