{{- if .Values.celeryWorker.autoscaling.enabled }}
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "casepro.fullname" . }}-celery-worker
  labels:
    {{- include "casepro.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "casepro.fullname" }}-celery-worker
  minReplicas: {{ .Values.celeryWorker.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.celeryWorker.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.celeryWorker.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: {{ .Values.celeryWorker.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.celeryWorker.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        targetAverageUtilization: {{ .Values.celeryWorker.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}
