{{- if .Values.collectstaticJob.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "casepro.fullname" . }}-collectstatic
  labels:
    {{- include "casepro.labels" . | nindent 4 }}
    app.kubernetes.io/component: collectstatic-job
  annotations:
    "helm.sh/hook": post-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
    "helm.sh/hook-weight": "0"
    checksum/secret: {{ include (print $.Template.BasePath "/secrets.yaml") . | sha256sum }}
    checksum/configmap: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
spec:
  template:
    spec:
      {{- with .Values.image.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.web.podSecurityContext | nindent 8 }}
      containers:
        - name: collecstatic-job
          securityContext:
            {{- toYaml .Values.web.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["python", "manage.py", "collectstatic", "--noinput"]
          envFrom:
            - configMapRef:
                name: {{ include "casepro.fullname" . }}
            - secretRef:
                name: {{ include "casepro.fullname" . }}
      restartPolicy: Never
  backoffLimit: 0
{{- end }}
