apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "casepro.fullname" . }}
  labels:
    {{- include "casepro.labels" . | nindent 4 }}
data:
{{- range $key, $value := .Values.envVariables }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
